### ISSUE TITLE
cleanlight world error

### ISSUE THREAD

**Issue by seema84** [bergerhealer/Light-Cleaner#11] opened 2018-12-04 16:29 UTC
**version:** 
Light-Cleaner 1.13.1-v1
spigot 1.13.2-R0.1-SNAPSHOT

**command:** 
cleanlight world world

**log:**
https://pastebin.com/S19fN0k1

**Comment by seema84** [comment] 2019-01-28 23:51
new error (also the same command) on the latest build

https://pastebin.com/eqF5HAG5

**Comment by Tsoccerguy3** [comment] 2019-07-01 08:13
I tried the cleanlight 1.14.2 release hoping it would woek with BKCommonLib-1.14.3-v1-SNAPSHOT
maybe the was a metrhod or name change between versions

BkCommonLib version:

BKCommonLib-1.14.3-v1-SNAPSHOT
Spigot version:

Paper 1.14.3 build 120
Problem or bug:

3:28:17 AM [INFO] The world is now being fixed, this may take very long!
3:28:17 AM [INFO] To view the fixing status, use /cleanlight status
3:28:17 AM [SEVERE] [REFLECTION] Failed to compile method body ([source error] no such class: org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.LongSet):
3:28:17 AM [SEVERE] [REFLECTION] public Object invoke(Object instance_raw, Object world_raw) {net.minecraft.server.v1_14_R1.WorldServer world=(net.minecraft.server.v1_14_R1.WorldServer) world_raw;{
3:28:17 AM ChunkProviderServer cps = world.getChunkProvider();
3:28:17 AM PlayerChunkMap pcm = cps.playerChunkMap;
3:28:17 AM RegionFileCache rfc = (RegionFileCache) pcm;
3:28:17 AM org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.LongSet coordSet;
3:28:17 AM org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.LongIterator iter;
3:28:17 AM coordSet = rfc.cache.keySet();
3:28:17 AM java.util.ArrayList result = new java.util.ArrayList(coordSet.size());
3:28:17 AM iter = coordSet.iterator();
3:28:17 AM while (iter.hasNext()) {
3:28:17 AM long coord = iter.nextLong();
3:28:17 AM int coord_x = ChunkCoordIntPair.getX(coord);
3:28:17 AM int coord_z = ChunkCoordIntPair.getZ(coord);
3:28:17 AM result.add(new com.bergerkiller.bukkit.common.bases.IntVector2(coord_x, coord_z));
3:28:17 AM }
3:28:17 AM return result;
3:28:17 AM }
3:28:17 AM return null;}
3:28:17 AM [SEVERE] [BKCommonLib] [BKCommonLib] Unhandled exception executing command 'cleanlight' in plugin LightCleaner v1.14.2-v1-SNAPSHOT
3:28:17 AM [WARNING] java.lang.RuntimeException: An exception occurred
3:28:17 AM [WARNING] Caused by: compile error: no such class: org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.LongSet
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.searchImports(MemberResolver.java:479)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:422)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.lookupClassByJvmName(MemberResolver.java:329)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.resolveJvmClassName(MemberResolver.java:519)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberCodeGen.resolveClassName(MemberCodeGen.java:1190)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atDeclarator(CodeGen.java:757)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Declarator.accept(Declarator.java:103)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.Javac.compileMethod(Javac.java:175)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.compiler.Javac.compile(Javac.java:102)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.CtNewMethod.make(CtNewMethod.java:79)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.dep.javassist.CtNewMethod.make(CtNewMethod.java:50)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker.makeMethodAndLog(GeneratedCodeInvoker.java:87)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker.create(GeneratedCodeInvoker.java:312)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.reflection.util.FastMethod$FastMethodInitProxy.init(FastMethod.java:168)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.reflection.util.FastMethod$FastMethodInitProxy.invoke(FastMethod.java:191)
3:28:17 AM [WARNING] at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122)
3:28:17 AM [WARNING] at com.bergerkiller.bukkit.common.internal.logic.RegionHandler_1_14.getRegions(RegionHandler_1_14.java:99)
3:28:17 AM [WARNING] at com.bergerkiller.bukkit.common.utils.WorldUtil.getWorldRegions(WorldUtil.java:1006)
3:28:17 AM [WARNING] at com.bergerkiller.bukkit.lightcleaner.util.RegionInfoMap.create(RegionInfoMap.java:63)
3:28:17 AM [WARNING] at com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskWorld.(LightingTaskWorld.java:17)
3:28:17 AM [WARNING] at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService.schedule(LightingService.java:169)
3:28:17 AM [WARNING] at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService.scheduleWorld(LightingService.java:128)
3:28:17 AM [WARNING] at com.bergerkiller.bukkit.lightcleaner.LightCleaner.command(LightCleaner.java:108)
3:28:17 AM [WARNING] at com.bergerkiller.bukkit.common.PluginBase.onCommand(PluginBase.java:894)
3:28:17 AM [WARNING] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
3:28:17 AM [WARNING] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
3:28:17 AM [WARNING] at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736)
3:28:17 AM [WARNING] at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:698)
3:28:17 AM [WARNING] at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:459)
3:28:17 AM [WARNING] at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:421)
3:28:17 AM [WARNING] at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
3:28:17 AM [WARNING] at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
3:28:17 AM [WARNING] at java.lang.Thread.run(Unknown Source)
3:28:17 AM [INFO] An internal error occured while executing this command
Expected behaviour:

to clean map of light glitches
Steps to reproduce:

enter /cleanlight world or /cleanlight world "name of map" or /cleanlight "any number"

**Comment by Tsoccerguy3** [comment] 2019-07-01 23:59
BKCommonLib-1.14.3-v1-SNAPSHOT issue is fixed to deal with 1.14.3 light cleaner

you can bump the version up to 1.14.3 by changing the version in the pom.xml and compiling . It seems to work .

Tip : when you convert from 1.13.2 to 1.14.3 , there is graphical render lag caused by lighting issues . If you have used WorldEdit or FAWE your game maps may be unplayable untill you run Lightcleaner world "maps name"

You can close this issue as fixed

**Comment by seema84** [comment] 2019-07-02 10:36
that what do you mean is not my problem (wrong issue)
i have only problems with a "large" light update

/cleanlight 10 works without a problem

**Comment by Tsoccerguy3** [comment] 2019-07-02 14:31
> 
> 
> that what do you mean is not my problem (wrong issue)
> i have only problems with a "large" light update
> 
> /cleanlight 10 works without a problem

I know what you mean . There is a long time lighting issue with vanilla minecraft that should be fixed in version 1.14.4 , Mojang is working on . The lighting NBT data per block and chunk does not get updated and can get corrupted on a bad shut down . If this happens the chunk will auto reset . Using lots of worldedit and FAWE does not allow the lighting to update . If you are updating to 1.14.x run /cleanlight world for all your maps in 1.13.x , the more memory you have the faster the lighting gets fixed . Then on Server Upgrade , going from 1.13.x to 1.14.x  use the switch --forceUpgrade --eraseCache . lightcleaner will pause if the server TPS is to low or memory becomes low . This issue is a general one for 1.14.x and why not recommended to update to unless you have the resources to fix coding errors.

Using the current BKCommonLib from july 1 , and the 1.14.2 work , speed is slow on first run and you need at least 6 gig of memory , try disabling plugins until all your maps re processed .

hope this helps .

**Comment by Tsoccerguy3** [comment] 2019-07-02 14:36
Lightcleaner needs to be Optimized for 1.13.x and1.14.x .

**Comment by Tsoccerguy3** [comment] 2019-07-02 14:41
As for 1.13.2 the crash is specific to memory issue only on spigot , this does not happen on Spigot Paper fork . I tested .

**Comment by bergerkiller** [comment] 2020-02-04 12:08
The NPE was either fixed or is no longer relevant, since I rewrote a portion of that. If it still occurs on the latest version (1.14.4-v1) you can open a new issue ticket with the updated stack trace.

> no such class: org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.LongSet
Longset was moved to a different path, and in the beginning there were errors like that when I was working on correcting this everywhere. It has been fixed for quite a while now. (In BKCommonLib)

The memory issues are still relevant, but are addressed by issue https://github.com/bergerhealer/Light-Cleaner/issues/3

Closing, can reopen if some portions of this issue are still relevant today

**Closed by bergerkiller** 2020-02-04 12:08 UTC
