### ISSUE TITLE
Lightcleaner console error

### ISSUE THREAD

**Issue by ryando123** [bergerhealer/Light-Cleaner#19] opened 2019-08-24 20:47 UTC
Using the latest BKCommonLib and Lightcleaner build from https://ci.mg-dev.eu
Server version 1.14.4

Error: https://pastebin.com/AaDcnLE0

**Comment by bergerkiller** [comment] 2020-02-04 12:00
> no such class: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap

This was caused by paperspigot moving the path of the class, it was fixed in BKCommonLib since then

**Closed by bergerkiller** 2020-02-04 12:00 UTC
