### ISSUE TITLE
Error with latest Paper Build "Server not supported"

### ISSUE THREAD

**Issue by zeronerve** [bergerhealer/Light-Cleaner#25] opened 2020-05-15 21:08 UTC
I just updated Paper to 254 and got this ...

`
[16:06:13 INFO]: zeronerve issued server command: /cleanlight 6
[16:06:16 WARN]: java.lang.NoSuchFieldException: e
[16:06:16 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
[16:06:16 WARN]:        at com.bergerkiller.bukkit.common.internal.logic.LightingHandler_1_14.<init>(LightingHandler_1_14.java:84)
[16:06:16 WARN]:        at com.bergerkiller.bukkit.common.internal.logic.LightingHandler.createInstance(LightingHandler.java:15)
[16:06:16 WARN]:        at com.bergerkiller.bukkit.common.internal.logic.LightingHandler.<clinit>(LightingHandler.java:10)
[16:06:16 WARN]:        at com.bergerkiller.bukkit.common.utils.WorldUtil.setSectionSkyLightAsync(WorldUtil.java:1103)
[16:06:16 WARN]:        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingChunkSection.saveToChunk(LightingChunkSection.java:180)
[16:06:16 WARN]:        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingChunk.saveToChunk(LightingChunk.java:381)
[16:06:16 WARN]:        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskBatch.apply(LightingTaskBatch.java:269)
[16:06:16 WARN]:        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskBatch.process(LightingTaskBatch.java:215)
[16:06:16 WARN]:        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService.run(LightingService.java:501)
[16:06:16 WARN]:        at com.bergerkiller.bukkit.common.AsyncTask$1.run(AsyncTask.java:47)
[16:06:16 ERROR]: [LightCleaner] Failed to process task: Cleaning 169 chunks near x=-352 z=256
java.lang.UnsupportedOperationException: Server not supported, initialization failed
        at com.bergerkiller.bukkit.common.internal.logic.LightingHandler_Broken.setSectionSkyLightAsync(LightingHandler_Broken.java:11) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.WorldUtil.setSectionSkyLightAsync(WorldUtil.java:1103) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingChunkSection.saveToChunk(LightingChunkSection.java:180) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingChunk.saveToChunk(LightingChunk.java:381) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskBatch.apply(LightingTaskBatch.java:269) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskBatch.process(LightingTaskBatch.java:215) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService.run(LightingService.java:501) ~[?:?]
        at com.bergerkiller.bukkit.common.AsyncTask$1.run(AsyncTask.java:47) ~[?:?]
`

**Comment by weeryan17** [comment] 2020-05-15 21:12
duplicate of issue #24 
you need to update bkcommonlib to a dev build available here [https://ci.mg-dev.eu/job/BKCommonLib/774/artifact/target/BKCommonLib-1.15.2-v4-SNAPSHOT.jar](https://ci.mg-dev.eu/job/BKCommonLib/774/artifact/target/BKCommonLib-1.15.2-v4-SNAPSHOT.jar)

**Closed** 2020-05-31 20:21 UTC
